
//This should contain all the information about our candidates (basically replace greenhouse)

{
	//This is all string data and can be entered from one form to initially enter a candidate in the system.  Recruitment team members should be able to update this at almost every step in the process.
	"firstName": "James",
	"lastName": "Hornung",
	"email": "hornung.james@gmail.com",
	"alternateEmail": "jhornung@ymail.com",
	"phone": "5127051184",
	"linkedIn": "https://www.linkedin.com/in/james-hornung-84526311b/",
	"website": "http://jameshornung.com/",
	"university": "University of Texas at Austin", //selected from a dropdown that is specific to the University chosen, generated by query to university collection
	"program": "FSF, Data, UIUX, etc",
	"role": "TA",
	"notes": "blah blah blah",//store specific info about candidate (former student, personal details, etc)
	"status": "HR Interview Pending",  //Dictates where in the flow the candidate is.  This field could be automatically updated on the submission of each form.  (ie when first entered in the system "HR Interview Pending", upon submission of HR Interview Form "Tech Interview Pending", etc)

	//Each interview stage can be it's own form.  That form data will be saved as an object
	"hrInterview": {
		"hrInterviewerName": "string",
		"dateOFHrInterview": date,
		"hrNotes": "Any interview specific details that the interviewer cares to save",
		"hrScores": [10, 8, 10, 9, "etc"]
	},
	"techInterview": {
		"techInterviewerName": "string",
		"dateOfTechInterview": date,
		"techNotes": "Any interview specific details that the interviewer cares to save",
		"techScores": [10, 8, 10, 9, "etc"]
	},
	"finalInterview": {
		"finalInterviewerName": "string",
		"dateOfFinalInterview": date,
		"finalNotes": "Any interview specific details that the interviewer cares to save",
		"finalScores": [10, 8, 10, 9, "etc"]
	},

	//This section will contain all the info to enter the candidate onto the role count, and trigger HR to send the offer letter.
	"offerCall": {
		"emailConnectWithMe": date,
		"verbalAgreement": true,
		"contemplatingOffer": false, //allow us to have a dashboard view of who is contemplating an offer
		"employmentLevel": "Primary", //or Substitute
		"primaryCohort": "String Data", //Selected from dropdown, all class dates for that university and program should be shown, but classes with primary roles filled should be "grayed out".  Primary cohort selection should only be available if employment level is selected as Primary -  selecting a primary cohort will place the candidate in a primary TA position for that cohort.
		"primaryCohort2": "String Date", //This will cover the unique situations where we hire a candidate for two primary roles at the same time (ie Daniel Cauperman and Rita Alfonso).  This selection will work the same as the primary cohort one.  

		//All selection other than primary will place the candidate in a substitute role
		"secondaryCohort": "String Data", //selected from dropdown, all cohorts available
		"tertiaryCohort": "String Data",
		"quaternaryCohort": "String Data",
		"quinaryCohort": "String Data",
		"compensation": {
			//default values, BUT with ability to be overidden
			"onboardingPayment": 500,
			"basePay": 5000,
			"completionBonus": 1000
		},
		//Default value false, upating to true will remove from role count.  This should allow us to have the functionality to remove a candidate from specific classes while keeping them in other.  (ie candidate wants to continue as sub, but wishes to quit their primary role.)
		"terminations": {
			"terminatedPrimary": false,
			"terminatedSecondary": false,
			"terminatedTertiary": false,
			"terminatedQuaternary": false,
			"terminatedQuinary": false,
		},
		"hiringNotes": "blah blah blah"
	},
	//Get with Cher to see what else needs to be stored here
	"onBoardingStatus": {
		"returnedContract": false,
		"onBoardingSheduled": true,
		"completedOnboardingSession": false,
		"onboardingNotes": "blah blah blah"
	}
};