
//This should contain all the information about our candidates (basically replace greenhouse)

{
	//This is all string data and can be entered from one form to initially enter a candidate in the system.  Recruitment team members should be able to update this at almost every step in the process.
	"firstName": "James",
	"lastName": "Hornung",
	"email": "hornung.james@gmail.com",
	"alternateEmail": "jhornung@ymail.com",
	"phone": "5127051184",
	"linkedIn": "https://www.linkedin.com/in/james-hornung-84526311b/",
	"website": "http://jameshornung.com/",
	//this school filed should be a string value that is selected from a dropdown, which is generated by the school names in the University collection
	"university": "University of Texas at Austin",
	//selected from a dropdown that is specific to the University chosen, generated by query to university collection
	"program": "FSF, Data, UIUX, etc",
	//store specific info about candidate (former student, personal details, etc)
	"role": "TA",
	"notes": "blah blah blah",
	//a status that dictates where in the flow the candidate is.  This field could be automatically updated on the submission of each form.  (ie when first entered in the system "HR Interview Pending", upon submission of HR Interview Form "Tech Interview Pending", etc)
	"status": "HR Interview Pending",
	//Each interview stage can be it's own form.  That form data will be saved as an object
	"hrInterview": {
		"hrInterviewerName": "string",
		"hrNotes": "Any interview specific details that the interviewer cares to save",
		"hrScores": [10, 8, 10, 9, "etc"]
	},
	"techInterview": {
		"techInterviewerName": "string",
		"techNotes": "Any interview specific details that the interviewer cares to save",
		"techScores": [10, 8, 10, 9, "etc"]
	},
	"finalInterview": {
		"finalInterviewerName": "string",
		"finalNotes": "Any interview specific details that the interviewer cares to save",
		"finalScores": [10, 8, 10, 9, "etc"]
	},
	"offerCall": {
		"verbalAgreement": true,
		"contemplatingOffer": false,
		"employmentLevel": "Primary", //or Substitute
		//primary cohort selection should only be available if employment level is selected as Primary
		"primaryCohort": "String Data", //selected from dropdown, all classes should be shown, but classes with primary roles filled should be "grayed out"
		//All selection other than primary will place the candidate in a substitute role
		"secondaryCohort": "String Data", //selected from dropdown, all cohorts available
		"tertiaryCohort": "String Data",
		"quaternaryCohort": "String Data",
		"quinaryCohort": "String Data",
		"compensation": {
			//default values, BUT with ability to be overidden
			"onboardingPayment": 500,
			"basePay": 5000,
			"completionBonus": 1000
		},
		//default value false, upating to true will remove from role count
		"terminations": {
			"terminatedPrimary": false,
			"terminatedSecondary": false,
			"terminatedTertiary": false,
			"terminatedQuaternary": false,
			"terminatedQuinary": false,
		},
		"hiringNotes": "blah blah blah"
	},
	//Get with Cher to see what else needs to be stored here
	"onBoardingStatus": {
		"returnedContract": false,
		"onBoardingSheduled": true,
		"completedOnboardingSession": false,
		"onboardingNotes": "blah blah blah"
	}
};